package project3;

import java.awt.Color;
import javax.swing.JFrame;

/*
 * CS 2365 OOP Spring 2020
 * Zegedam Zegeye
 */
public class board extends javax.swing.JFrame {
    project3.charDisc p = new project3.charDisc();
    int hp1;
    int hp2;
    int hp3;
    int hp4;
    int hp5;
    int hp6;
    int hp7;
    int hp8;
    int arrow1;
    int arrow2;
    int arrow3;
    int arrow4;
    int arrow5;
    int arrow6;
    int arrow7;
    int arrow8;
    int Tarrow;
    String ch1 = "You may take an arrow instead\nof losing a life point\n(except to Indians or Dynamite)";
    String ch2 = "You never lose life points to the\nGatling Gun";
    String ch3 = "You may re-roll a dynamite\n(not if you roll three or more)";
    String ch4 = "Each time you lose a life point,\nyou may discard one of your arrows\n(still lose the life point)";
    String ch5 = "You can use 1 shot as 2 shot and\nvice-versa";
    String ch6 = "Shooting range increases by one";
    String ch7 = "When a player makes you lose one\nor more life points, he must\ntake an arrow";
    String ch8 = "At the beginning of your turn,\nany player of your choice gains\none life point(including yourself)";
    String ch9 = "If you have four life points or\nless, you gain two if you use\nbeer for yourself";
    String ch10 = "Once per turn, you can use a\nbeer to double your shooting\ndamage";
    String ch11= "You never lose more than one\nlife point to Indians";
    String ch12 = "If you didn’t roll any bullseye,\nyou gain two life points\n(applies to end of your turn)";
    String ch13 = "For each gattling you may\ndiscard one arrow from any player";
    String ch14 = "Each time another player is\neliminated, you gain two life\npoints";
    String ch15 = "You may make one extra re-roll\n(max of four)";
    String ch16 = "you only need two gattling dice\nto use the Gatling Gun\n(Only use Gatling gun once per turn)";
    String name1 = "BART CASSIDY";
    String name2 = "PAUL REGRET";
    String name3 = "BLACK JACK";
    String name4 = "PEDRO RAMERIEZ";
    String name5 = "CALAMITY JANET";
    String name6 = "ROSE DOOLAN";
    String name7 = "EL GRINGO";
    String name8 = "SID KETCHUM";
    String name9 = "JESSE JONES";
    String name10 = "SLAB THE KILLER";
    String name11 = "JOURDONNAIS";
    String name12 = "SUZY LAFAYETTE";
    String name13 = "KIT CARLSON";
    String name14 = "VULTURE SAM";
    String name15 = "LUCKY DUKE";
    String name16 = "WILLY THE KID";
    
    /**
     * Creates new form game
     */
    public board() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        p3 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p8 = new javax.swing.JLabel();
        n1 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        n2 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        n3 = new javax.swing.JLabel();
        h4 = new javax.swing.JLabel();
        n4 = new javax.swing.JLabel();
        h5 = new javax.swing.JLabel();
        n5 = new javax.swing.JLabel();
        h6 = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        h7 = new javax.swing.JLabel();
        n7 = new javax.swing.JLabel();
        h8 = new javax.swing.JLabel();
        n8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pc8 = new javax.swing.JLabel();
        pc7 = new javax.swing.JLabel();
        pc6 = new javax.swing.JLabel();
        pc5 = new javax.swing.JLabel();
        pc4 = new javax.swing.JLabel();
        pc3 = new javax.swing.JLabel();
        pc2 = new javax.swing.JLabel();
        pa1 = new javax.swing.JLabel();
        A1 = new javax.swing.JLabel();
        pa8 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        pa7 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        pa6 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        pa5 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        pa4 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        pa3 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        pa2 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(153, 102, 0));

        p3.setForeground(new java.awt.Color(255, 255, 255));
        p3.setText("P3 (AI)");

        p7.setForeground(new java.awt.Color(255, 255, 255));
        p7.setText("P7 (AI)");

        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("P2 (AI)");

        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p1.setText("User");

        p6.setForeground(new java.awt.Color(255, 255, 255));
        p6.setText("P6 (AI)");

        p4.setForeground(new java.awt.Color(255, 255, 255));
        p4.setText("P4 (AI)");

        p5.setForeground(new java.awt.Color(255, 255, 255));
        p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p5.setText("P5 (AI)");

        p8.setForeground(new java.awt.Color(255, 255, 255));
        p8.setText("P8 (AI)");

        n1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n1.setForeground(new java.awt.Color(0, 0, 255));
        n1.setText("10");

        h1.setForeground(new java.awt.Color(255, 255, 255));
        h1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        h1.setText("Health:");

        h2.setForeground(new java.awt.Color(255, 255, 255));
        h2.setText("Health:");

        n2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n2.setForeground(new java.awt.Color(0, 0, 255));
        n2.setText("10");

        h3.setForeground(new java.awt.Color(255, 255, 255));
        h3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        h3.setText("Health:");

        n3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n3.setForeground(new java.awt.Color(0, 0, 255));
        n3.setText("10");

        h4.setForeground(new java.awt.Color(255, 255, 255));
        h4.setText("Health:");

        n4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n4.setForeground(new java.awt.Color(0, 0, 255));
        n4.setText("10");

        h5.setForeground(new java.awt.Color(255, 255, 255));
        h5.setText("Health:");

        n5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n5.setForeground(new java.awt.Color(0, 0, 255));
        n5.setText("10");

        h6.setForeground(new java.awt.Color(255, 255, 255));
        h6.setText("Health:");

        n6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n6.setForeground(new java.awt.Color(0, 0, 255));
        n6.setText("10");

        h7.setForeground(new java.awt.Color(255, 255, 255));
        h7.setText("Health:");

        n7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n7.setForeground(new java.awt.Color(0, 0, 255));
        n7.setText("10");

        h8.setForeground(new java.awt.Color(255, 255, 255));
        h8.setText("Health:");

        n8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        n8.setForeground(new java.awt.Color(0, 0, 255));
        n8.setText("10");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/Outlaw.PNG"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character3.PNG"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Description");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sheriff =");

        pc8.setForeground(new java.awt.Color(255, 255, 255));
        pc8.setText("Character");

        pc7.setForeground(new java.awt.Color(255, 255, 255));
        pc7.setText("Character");

        pc6.setForeground(new java.awt.Color(255, 255, 255));
        pc6.setText("Character ");

        pc5.setForeground(new java.awt.Color(255, 255, 255));
        pc5.setText("Character");

        pc4.setForeground(new java.awt.Color(255, 255, 255));
        pc4.setText("Character");

        pc3.setForeground(new java.awt.Color(255, 255, 255));
        pc3.setText("Character");

        pc2.setForeground(new java.awt.Color(255, 255, 255));
        pc2.setText("Character");

        pa1.setForeground(new java.awt.Color(255, 255, 255));
        pa1.setText("Arrow:");

        A1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A1.setForeground(new java.awt.Color(0, 0, 255));
        A1.setText("0");

        pa8.setForeground(new java.awt.Color(255, 255, 255));
        pa8.setText("Arrow:");

        A8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A8.setForeground(new java.awt.Color(0, 0, 255));
        A8.setText("0");

        pa7.setForeground(new java.awt.Color(255, 255, 255));
        pa7.setText("Arrow:");

        A7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A7.setForeground(new java.awt.Color(0, 0, 255));
        A7.setText("0");

        pa6.setForeground(new java.awt.Color(255, 255, 255));
        pa6.setText("Arrow:");

        A6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A6.setForeground(new java.awt.Color(0, 0, 255));
        A6.setText("0");

        pa5.setForeground(new java.awt.Color(255, 255, 255));
        pa5.setText("Arrow:");

        A5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A5.setForeground(new java.awt.Color(0, 0, 255));
        A5.setText("0");

        pa4.setForeground(new java.awt.Color(255, 255, 255));
        pa4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pa4.setText("Arrow:");

        A4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A4.setForeground(new java.awt.Color(0, 0, 255));
        A4.setText("0");

        pa3.setForeground(new java.awt.Color(255, 255, 255));
        pa3.setText("Arrow:");

        A3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A3.setForeground(new java.awt.Color(0, 0, 255));
        A3.setText("0");

        pa2.setForeground(new java.awt.Color(255, 255, 255));
        pa2.setText("Arrow:");

        A2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        A2.setForeground(new java.awt.Color(0, 0, 255));
        A2.setText("0");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Arrow:");

        TA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TA.setForeground(new java.awt.Color(0, 0, 255));
        TA.setText("10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(p3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(h8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n8))
                                    .addComponent(pc3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(h7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n7))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(pa3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A3))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(pa2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A2))
                                    .addComponent(pc4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pc2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(pa4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(A4))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(h3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(p8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(h4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(n4))
                                .addComponent(pc5)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(pa5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(A5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(p4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(300, 300, 300)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(6, 6, 6)))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(pa1)
                                        .addComponent(h1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(n1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(A1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(240, 240, 240))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(h5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(h6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(n6)))
                                .addGap(84, 84, 84))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pc8, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(pc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(pa8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A8))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(pa7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(A7)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pc6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(h2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n2))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(pa6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(A6))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n4)
                    .addComponent(h4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pc5)
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pa5)
                    .addComponent(A5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p4))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(h2)
                        .addComponent(n2))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(h3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(n3)))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pc6)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pa6)
                            .addComponent(A6))
                        .addGap(18, 18, 18)
                        .addComponent(p7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(h6)
                            .addComponent(n6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pc7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pa7)
                            .addComponent(A7))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(pc4)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A4))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p3)
                            .addComponent(jLabel5)
                            .addComponent(TA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h8)
                            .addComponent(n8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pc3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pa3)
                            .addComponent(A3))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(p8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(h5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(n5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pc8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pa8)
                            .addComponent(A8))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(p2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(h7)
                            .addComponent(n7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pc2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pa2)
                            .addComponent(A2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(n1)
                    .addComponent(h1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pa1)
                    .addComponent(A1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 835, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void pChoice(int ch){
        if(ch == 1){
            seen();
            p2.setVisible(false);
            p4.setVisible(false);
            p6.setVisible(false);
            p8.setVisible(false);
            h7.setVisible(false);
            h3.setVisible(false);
            h2.setVisible(false);
            h5.setVisible(false);
            n7.setVisible(false);
            n3.setVisible(false);
            n2.setVisible(false);
            n5.setVisible(false);
            A2.setVisible(false);
            A4.setVisible(false);
            A6.setVisible(false);
            A8.setVisible(false);
            pa2.setVisible(false);
            pa4.setVisible(false);
            pa6.setVisible(false);
            pa8.setVisible(false);
            pc2.setVisible(false);
            pc4.setVisible(false);
            pc6.setVisible(false);
            pc8.setVisible(false);

        }
        else if(ch == 2){
            seen();
            p3.setVisible(false);
            p5.setVisible(false);
            p7.setVisible(false);
            h8.setVisible(false);
            h4.setVisible(false);
            h6.setVisible(false);
            n8.setVisible(false);
            n4.setVisible(false);
            n6.setVisible(false);
            A3.setVisible(false);
            A5.setVisible(false);
            A7.setVisible(false);
            pa3.setVisible(false);
            pa5.setVisible(false);
            pa7.setVisible(false);
            pc3.setVisible(false);
            pc5.setVisible(false);
            pc7.setVisible(false);
        }
        else if(ch == 3){
            seen();
            p3.setVisible(false);
            p7.setVisible(false);
            h8.setVisible(false);
            h6.setVisible(false);
            n8.setVisible(false);
            n6.setVisible(false);
            A3.setVisible(false);
            A7.setVisible(false);
            pa3.setVisible(false);
            pa7.setVisible(false);
            pc3.setVisible(false);
            pc7.setVisible(false);
        }
        else if(ch == 4){
            seen();
            p8.setVisible(false);
            h5.setVisible(false);
            n5.setVisible(false);
            A8.setVisible(false);
            pa8.setVisible(false);
            pc8.setVisible(false);
        }
        else if(ch == 5){
            seen();
        }
    }
    
    public void setRole(String role, String player){
        if("p1".equals(player)){
            if("Outlaw".equals(role)){
                   jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/Outlaw.PNG")));
                }
            else if("Deputy".equals(role)){
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/Deputy.PNG")));
               }
            else if("Sheriff".equals(role)){
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/Sheriff.PNG")));
                jLabel4.setText("Sheriff = User");
               }
            else if("Renegade".equals(role)){
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/Renegade.PNG")));
               }
           }
        else if("p2".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 6");
                }
            }
        else if("p3".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 7");
                }
            }
        else if("p4".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 2");
                }
            }
        else if("p5".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 3");
                }
            }
        else if("p6".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 1");
                }
            }
        else if("p7".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 5");
                }
            }
        else if("p8".equals(player)){
            if("Sheriff".equals(role)){
                jLabel4.setText("Sheriff = AI 4");
                }
            }
        }
    
    public void setChar(String name, String player){
        if("p1".equals(player)||"p0".equals(player)){
            if(name.equals(name1)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character1.PNG")));
                p.desc(ch1);
                p.title(name1);
            }
            else if(name.equals(name2)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character2.PNG")));
                p.desc(ch2);
                p.title(name2);
            }
            else if(name.equals(name3)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character3.PNG")));
                p.desc(ch3);
                p.title(name3);
            }
            else if(name.equals(name4)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character4.PNG")));
                p.desc(ch4);
                p.title(name4);
            }
            else if(name.equals(name5)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character5.PNG")));
                p.desc(ch5);
                p.title(name5);
            }
            else if(name.equals(name6)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character6.PNG")));
                p.desc(ch6);
                p.title(name6);
            }
            else if(name.equals(name7)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character7.PNG")));
                p.desc(ch7);
                p.title(name7);
            }
            else if(name.equals(name8)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character8.PNG")));
                p.desc(ch8);
                p.title(name8);
            }
            else if(name.equals(name9)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character9.PNG")));
                p.desc(ch9);
                p.title(name9);
            }
            else if(name.equals(name10)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character10.PNG")));
                p.desc(ch10);
                p.title(name10);
            }
            else if(name.equals(name11)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character11.PNG")));
                p.desc(ch11);
                p.title(name11);
            }
            else if(name.equals(name12)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character12.PNG")));
                p.desc(ch12);
                p.title(name12);
            }
            else if(name.equals(name13)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character13.PNG")));
                p.desc(ch13);
                p.title(name13);
            }
            else if(name.equals(name14)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character14.PNG")));
                p.desc(ch14);
                p.title(name14);
            }
            else if(name.equals(name15)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character15.PNG")));
                p.desc(ch15);
                p.title(name15);
            }
            else if(name.equals(name16)){
                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project3/character16.PNG")));
                p.desc(ch16);
                p.title(name16);
            }
        }
        else if("p2".equals(player)){
            if(name.equals(name1)){
                pc2.setText(name1);
            }
            else if(name.equals(name2)){
                pc2.setText(name2);
            }
            else if(name.equals(name3)){
                pc2.setText(name3);
            }
            else if(name.equals(name4)){
                pc2.setText(name4);
            }
            else if(name.equals(name5)){
                pc2.setText(name5);
            }
            else if(name.equals(name6)){
                pc2.setText(name6);
            }
            else if(name.equals(name7)){
                pc2.setText(name7);
            }
            else if(name.equals(name8)){
                pc2.setText(name8);
            }
            else if(name.equals(name9)){
                pc2.setText(name9);
            }
            else if(name.equals(name10)){
                pc2.setText(name10);
            }
            else if(name.equals(name11)){
                pc2.setText(name11);
            }
            else if(name.equals(name12)){
                pc2.setText(name12);
            } 
            else if(name.equals(name13)){
                pc2.setText(name13);
            }
            else if(name.equals(name14)){
                pc2.setText(name14);
            }
            else if(name.equals(name15)){
                pc2.setText(name15);
            }
            else if(name.equals(name16)){
                pc2.setText(name16);
            }
        }
        else if("p3".equals(player)){
            if(name.equals(name1)){
                pc3.setText(name1);
            }
            else if(name.equals(name2)){
                pc3.setText(name2);
            }
            else if(name.equals(name3)){
                pc3.setText(name3);
            }
            else if(name.equals(name4)){
                pc3.setText(name4);
            }
            else if(name.equals(name5)){
                pc3.setText(name5);
            }
            else if(name.equals(name6)){
                pc3.setText(name6);
            }
            else if(name.equals(name7)){
                pc3.setText(name7);
            }
            else if(name.equals(name8)){
                pc3.setText(name8);
            }
            else if(name.equals(name9)){
                pc3.setText(name9);
            }
            else if(name.equals(name10)){
                pc3.setText(name10);
            }
            else if(name.equals(name11)){
                pc3.setText(name11);
            }
            else if(name.equals(name12)){
                pc3.setText(name12);
            } 
            else if(name.equals(name13)){
                pc3.setText(name13);
            }
            else if(name.equals(name14)){
                pc3.setText(name14);
            }
            else if(name.equals(name15)){
                pc3.setText(name15);
            }
            else if(name.equals(name16)){
                pc3.setText(name16);
            }
        }
        else if("p4".equals(player)){
            if(name.equals(name1)){
                pc4.setText(name1);
            }
            else if(name.equals(name2)){
                pc4.setText(name2);
            }
            else if(name.equals(name3)){
                pc4.setText(name3);
            }
            else if(name.equals(name4)){
                pc4.setText(name4);
            }
            else if(name.equals(name5)){
                pc4.setText(name5);
            }
            else if(name.equals(name6)){
                pc4.setText(name6);
            }
            else if(name.equals(name7)){
                pc4.setText(name7);
            }
            else if(name.equals(name8)){
                pc4.setText(name8);
            }
            else if(name.equals(name9)){
                pc4.setText(name9);
            }
            else if(name.equals(name10)){
                pc4.setText(name10);
            }
            else if(name.equals(name11)){
                pc4.setText(name11);
            }
            else if(name.equals(name12)){
                pc4.setText(name12);
            } 
            else if(name.equals(name13)){
                pc4.setText(name13);
            }
            else if(name.equals(name14)){
                pc4.setText(name14);
            }
            else if(name.equals(name15)){
                pc4.setText(name15);
            }
            else if(name.equals(name16)){
                pc4.setText(name16);
            }
        }
        else if("p5".equals(player)||"p10".equals(player)){
            if(name.equals(name1)){
                pc5.setText(name1);
            }
            else if(name.equals(name2)){
                pc5.setText(name2);
            }
            else if(name.equals(name3)){
                pc5.setText(name3);
            }
            else if(name.equals(name4)){
                pc5.setText(name4);
            }
            else if(name.equals(name5)){
                pc5.setText(name5);
            }
            else if(name.equals(name6)){
                pc5.setText(name6);
            }
            else if(name.equals(name7)){
                pc5.setText(name7);
            }
            else if(name.equals(name8)){
                pc5.setText(name8);
            }
            else if(name.equals(name9)){
                pc5.setText(name9);
            }
            else if(name.equals(name10)){
                pc5.setText(name10);
            }
            else if(name.equals(name11)){
                pc5.setText(name11);
            }
            else if(name.equals(name12)){
                pc5.setText(name12);
            } 
            else if(name.equals(name13)){
                pc5.setText(name13);
            }
            else if(name.equals(name14)){
                pc5.setText(name14);
            }
            else if(name.equals(name15)){
                pc5.setText(name15);
            }
            else if(name.equals(name16)){
                pc5.setText(name16);
            }
        }
        else if("p6".equals(player)){
            if(name.equals(name1)){
                pc6.setText(name1);
            }
            else if(name.equals(name2)){
                pc6.setText(name2);
            }
            else if(name.equals(name3)){
                pc6.setText(name3);
            }
            else if(name.equals(name4)){
                pc6.setText(name4);
            }
            else if(name.equals(name5)){
                pc6.setText(name5);
            }
            else if(name.equals(name6)){
                pc6.setText(name6);
            }
            else if(name.equals(name7)){
                pc6.setText(name7);
            }
            else if(name.equals(name8)){
                pc6.setText(name8);
            }
            else if(name.equals(name9)){
                pc6.setText(name9);
            }
            else if(name.equals(name10)){
                pc6.setText(name10);
            }
            else if(name.equals(name11)){
                pc6.setText(name11);
            }
            else if(name.equals(name12)){
                pc6.setText(name12);
            } 
            else if(name.equals(name13)){
                pc6.setText(name13);
            }
            else if(name.equals(name14)){
                pc6.setText(name14);
            }
            else if(name.equals(name15)){
                pc6.setText(name15);
            }
            else if(name.equals(name16)){
                pc6.setText(name16);
            }
        }
        else if("p7".equals(player)){
            if(name.equals(name1)){
                pc7.setText(name1);
            }
            else if(name.equals(name2)){
                pc7.setText(name2);
            }
            else if(name.equals(name3)){
                pc7.setText(name3);
            }
            else if(name.equals(name4)){
                pc7.setText(name4);
            }
            else if(name.equals(name5)){
                pc7.setText(name5);
            }
            else if(name.equals(name6)){
                pc7.setText(name6);
            }
            else if(name.equals(name7)){
                pc7.setText(name7);
            }
            else if(name.equals(name8)){
                pc7.setText(name8);
            }
            else if(name.equals(name9)){
                pc7.setText(name9);
            }
            else if(name.equals(name10)){
                pc7.setText(name10);
            }
            else if(name.equals(name11)){
                pc7.setText(name11);
            }
            else if(name.equals(name12)){
                pc7.setText(name12);
            } 
            else if(name.equals(name13)){
                pc7.setText(name13);
            }
            else if(name.equals(name14)){
                pc7.setText(name14);
            }
            else if(name.equals(name15)){
                pc7.setText(name15);
            }
            else if(name.equals(name16)){
                pc7.setText(name16);
            }
        }
        else if("p8".equals(player)){
            if(name.equals(name1)){
                pc8.setText(name1);
            }
            else if(name.equals(name2)){
                pc8.setText(name2);
            }
            else if(name.equals(name3)){
                pc8.setText(name3);
            }
            else if(name.equals(name4)){
                pc8.setText(name4);
            }
            else if(name.equals(name5)){
                pc8.setText(name5);
            }
            else if(name.equals(name6)){
                pc8.setText(name6);
            }
            else if(name.equals(name7)){
                pc8.setText(name7);
            }
            else if(name.equals(name8)){
                pc8.setText(name8);
            }
            else if(name.equals(name9)){
                pc8.setText(name9);
            }
            else if(name.equals(name10)){
                pc8.setText(name10);
            }
            else if(name.equals(name11)){
                pc8.setText(name11);
            }
            else if(name.equals(name12)){
                pc8.setText(name12);
            } 
            else if(name.equals(name13)){
                pc8.setText(name13);
            }
            else if(name.equals(name14)){
                pc8.setText(name14);
            }
            else if(name.equals(name15)){
                pc8.setText(name15);
            }
            else if(name.equals(name16)){
                pc8.setText(name16);
            }
        }
    }
    
    public void update_Health(int value, String player){
        if("p1".equals(player)){
            hp1 = value;
            String s1 = Integer.toString(hp1);
            n1.setText(s1);
            int N1 = Integer.parseInt(n1.getText());
            if(N1 <= 0)
                n1.setForeground(Color.red);
            if(n1.getText().contains("-")){
                n1.setText("0");
            }
        }
        else if("p2".equals(player)){
            hp2 = value;
            String s2 = Integer.toString(hp2);
            n1.setText(s2);
            int N2 = Integer.parseInt(n2.getText());
            if(N2 <= 0)
                n2.setForeground(Color.red);
            if(n2.getText().contains("-")){
                n2.setText("0");
            }
            
        }
        else if("p3".equals(player)){
            hp3 = value;
            String s3 = Integer.toString(hp3);
            n1.setText(s3);
            int N3 = Integer.parseInt(n3.getText());
            if(N3 <= 0)
                n3.setForeground(Color.red);
            if(n3.getText().contains("-")){
                n3.setText("0");
            }
        }
        else if("p4".equals(player)){
            hp4 = value;
            String s4 = Integer.toString(hp4);
            n1.setText(s4);
            int N4 = Integer.parseInt(n4.getText());
            if(N4 <= 0)
                n4.setForeground(Color.red);
            if(n4.getText().contains("-")){
                n4.setText("0");
            }
        }
        else if("p5".equals(player)){
            hp5 = value;
            String s5 = Integer.toString(hp5);
            n1.setText(s5);
            int N5 = Integer.parseInt(n5.getText());
            if(N5 <= 0)
                n5.setForeground(Color.red);
            if(n5.getText().contains("-")){
                n5.setText("0");
            }
        }
        else if("p6".equals(player)){
            hp6 = value;
            String s6 = Integer.toString(hp6);
            n1.setText(s6);
            int N6 = Integer.parseInt(n6.getText());
            if(N6 <= 0)
                n6.setForeground(Color.red);
            if(n6.getText().contains("-")){
                n6.setText("0");
            }
        }
        else if("p7".equals(player)){
            hp7 = value;
            String s7 = Integer.toString(hp7);
            n1.setText(s7);
            int N7 = Integer.parseInt(n7.getText());
            if(N7 <= 0)
                n7.setForeground(Color.red);
            if(n7.getText().contains("-")){
                n7.setText("0");
            }
        }
        else if("p8".equals(player)){
            hp8 = value;
            String s8 = Integer.toString(hp8);
            n1.setText(s8);
            int N8 = Integer.parseInt(n8.getText());
            if(N8 <= 0)
                n8.setForeground(Color.red);
            if(n8.getText().contains("-")){
                n8.setText("0");
            }
        }
    }
    public void pArrow(int value, String player){
            if("p1".equals(player)){
            arrow1 = value;
            String s1 = Integer.toString(arrow1);
            A1.setText(s1);
        }
            else if("p2".equals(player)){
            arrow2 = value;
            String s2 = Integer.toString(arrow2);
            A2.setText(s2);
        }
            else if("p3".equals(player)){
            arrow3 = value;
            String s3 = Integer.toString(arrow3);
            A3.setText(s3);
        }
            else if("p4".equals(player)){
            arrow4 = value;
            String s4 = Integer.toString(arrow4);
            A4.setText(s4);
        }   
            else if("p5".equals(player)){
            arrow5 = value;
            String s5 = Integer.toString(arrow5);
            A5.setText(s5);
        }
            else if("p6".equals(player)){
            arrow6 = value;
            String s6 = Integer.toString(arrow6);
            A6.setText(s6);
        } 
            else if("p7".equals(player)){
            arrow7 = value;
            String s7 = Integer.toString(arrow7);
            A7.setText(s7);
        }
            else if("p8".equals(player)){
            arrow8 = value;
            String s8 = Integer.toString(arrow8);
            A8.setText(s8);
        } 
    }
    
    public void tArrow(int value){
        Tarrow = value;
        String ta = Integer.toString(Tarrow);
        TA.setText(ta);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        p.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        p.setLocation(957, 826);
        p.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void seen(){
                p6.setVisible(true);
                p4.setVisible(true);
                p5.setVisible(true);
                p8.setVisible(true);
                p7.setVisible(true);
                p2.setVisible(true);
                p3.setVisible(true);
                h2.setVisible(true);
                h3.setVisible(true);
                h4.setVisible(true);
                h5.setVisible(true);
                h6.setVisible(true);
                h7.setVisible(true);
                h8.setVisible(true);
                n2.setVisible(true);
                n3.setVisible(true);
                n4.setVisible(true);
                n5.setVisible(true);
                n6.setVisible(true);
                n7.setVisible(true);
                n8.setVisible(true);
                A6.setVisible(true);
                A4.setVisible(true);
                A5.setVisible(true);
                A8.setVisible(true);
                A7.setVisible(true);
                A2.setVisible(true);
                A3.setVisible(true);    
                pa6.setVisible(true);
                pa4.setVisible(true);
                pa5.setVisible(true);
                pa8.setVisible(true);
                pa7.setVisible(true);
                pa2.setVisible(true);
                pa3.setVisible(true);
                pc6.setVisible(true);
                pc4.setVisible(true);
                pc5.setVisible(true);
                pc8.setVisible(true);
                pc7.setVisible(true);
                pc2.setVisible(true);
                pc3.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A1;
    private javax.swing.JLabel A2;
    private javax.swing.JLabel A3;
    private javax.swing.JLabel A4;
    private javax.swing.JLabel A5;
    private javax.swing.JLabel A6;
    private javax.swing.JLabel A7;
    private javax.swing.JLabel A8;
    private javax.swing.JLabel TA;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel n1;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel n5;
    private javax.swing.JLabel n6;
    private javax.swing.JLabel n7;
    private javax.swing.JLabel n8;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    private javax.swing.JLabel p8;
    private javax.swing.JLabel pa1;
    private javax.swing.JLabel pa2;
    private javax.swing.JLabel pa3;
    private javax.swing.JLabel pa4;
    private javax.swing.JLabel pa5;
    private javax.swing.JLabel pa6;
    private javax.swing.JLabel pa7;
    private javax.swing.JLabel pa8;
    private javax.swing.JLabel pc2;
    private javax.swing.JLabel pc3;
    private javax.swing.JLabel pc4;
    private javax.swing.JLabel pc5;
    private javax.swing.JLabel pc6;
    private javax.swing.JLabel pc7;
    private javax.swing.JLabel pc8;
    // End of variables declaration//GEN-END:variables
}
